### ISSUE TITLE
Wrong usage of Include/Exclude

### ISSUE THREAD

**Issue by ericbottard** [sample-accelerators/spring-smtp-gateway#1]
I doubt
https://github.com/sample-accelerators/spring-smtp-gateway/blob/3175027ac9259c8a5bcc7fda6b66a9bfedf23445/accelerator.yaml#L70-L73

is what you want to do @gm2552.

The "exclude" line lets through *everything* that is not excluded, which is going to be merged with your other blocks.

**Comment by gm2552** [comment]
First attempt at an accelerator so I appreciate the feedback.  I'll go back and take a look at this, but I do believe you are correct.

**Comment by gm2552** [comment]
Address with commit 89cddd4.
